export type ViewType =
  | "dashboard"
  | "patients"
  | "triage"
  | "referrals"
  | "appointments"
  | "asha"
  | "ai-chatbot"
  | "inventory"
  | "admin-doctors"
  | "followups"
  | "sos"
  | "reports"
  | "settings"
  | "design-system"
  | "register-admin"
  | "register-doctor";
